on: push
name: Run tests Action
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        uses: cedrickring/golang-action@1.6.0
        with:
          args: go test ./...